config/routes.rb
LargeDb2::Application.routes.draw do
  resources :kine

end

app/models/cow.rb
class Cow < ActiveRecord::Base
  def self.search(name, owner)
    if (!name.nil? && ! name.empty?) && (! owner.nil? && ! owner.empty?)
      Cow.where(['name LIKE ? AND owner_id = ?', "%#{name}%", owner])
    elsif (! name.nil? && ! name.empty? )
      Cow.where(['name LIKE ?', "%#{name}%"])
    elsif (!owner.nil? && ! owner.empty? )
      Cow.where(owner_id:  owner)
    else
      Cow.all
    end
  end

  def self.searchOwner(search)
    if search
      Cow.where(['owner_id = ?', search])
    else
      Cow.all
    end
  end

  def self.pluck2hash( *col )
    Cow.pluck( *col ).map{|rec| Hash[*col.zip(rec).flatten]}
  end

  def self.pluck2array( *col )
    Cow.pluck( *col ).map{|rec| Array[*col.zip(rec)]}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kine_controller.rb
class KineController < ApplicationController
  before_action :set_cow, only: [:show, :edit, :update, :destroy]

  # GET /kine
  # GET /kine.json
  def index
    if ! (params[:search].nil? && params[:search_owner].nil?)
      @kine = Cow.search(params[:search], params[:search_owner])
      @kineHash = @kine.pluck2hash(:id, :name, :ear, :birth, :owner_id, :t01, :t02, :t03, :t04, :t05, :t06, :t07, :t08, :t09, :t10) #, :t11, :t12, :t13, :t14, :t15, :t16, :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24, :t25, :t26, :t27, :t28, :t29, :t30, :t31, :t32, :t33, :t34, :t35, :t36, :t37, :t38, :t39, :t40, :t41, :t42, :t43, :t44, :t45, :t46, :t47, :t48, :t49, :t50, :t51, :t52, :t53, :t54, :t55, :t56, :t57, :t58, :t59, :t60, :t61, :t62, :t63, :t64, :t65, :t66, :t67, :t68, :t69, :t70, :t71, :t72, :t73, :t74, :t75, :t76, :t77, :t78, :t79, :t80, :t81, :t82, :t83, :t84, :t85, :t86, :t87, :t88, :t89, :t90, :t91, :t92, :t93, :t94, :t95, :t96, :t97, :t98, :t99)
#    @kineArray = @kine.pluck2array(:id, :name, :ear, :birth, :owner_id )
      #, :t01, :t02, :t03, :t04, :t05, :t06, :t07, :t08, :t09, :t10, :t11, :t12, :t13, :t14, :t15, :t16, :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24, :t25, :t26, :t27, :t28, :t29, :t30, :t31, :t32, :t33, :t34, :t35, :t36, :t37, :t38, :t39, :t40, :t41, :t42, :t43, :t44, :t45, :t46, :t47, :t48, :t49, :t50, :t51, :t52, :t53, :t54, :t55, :t56, :t57, :t58, :t59, :t60, :t61, :t62, :t63, :t64, :t65, :t66, :t67, :t68, :t69, :t70, :t71, :t72, :t73, :t74, :t75, :t76, :t77, :t78, :t79, :t80, :t81, :t82, :t83, :t84, :t85, :t86, :t87, :t88, :t89, :t90, :t91, :t92, :t93, :t94, :t95, :t96, :t97, :t98, :t99)
    else
      @kine = []
    end
  end

  # GET /kine/1
  # GET /kine/1.json
  def show
  end

  # GET /kine/new
  def new
    @cow = Cow.new
  end

  # GET /kine/1/edit
  def edit
  end

  # POST /kine
  # POST /kine.json
  def create
    @cow = Cow.new(cow_params)

    respond_to do |format|
      if @cow.save
        format.html { redirect_to @cow, notice: 'Cow was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cow }
      else
        format.html { render action: 'new' }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kine/1
  # PATCH/PUT /kine/1.json
  def update
    respond_to do |format|
      if @cow.update(cow_params)
        format.html { redirect_to @cow, notice: 'Cow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kine/1
  # DELETE /kine/1.json
  def destroy
    @cow.destroy
    respond_to do |format|
      format.html { redirect_to kine_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cow
      @cow = Cow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cow_params
      params.require(:cow).permit(:name, :ear, :birth, :owner_id, :t01, :t02, :t03, :t04, :t05, :t06, :t07, :t08, :t09, :t10, :t11, :t12, :t13, :t14, :t15, :t16, :t17, :t18, :t19, :t20, :t21, :t22, :t23, :t24, :t25, :t26, :t27, :t28, :t29, :t30, :t31, :t32, :t33, :t34, :t35, :t36, :t37, :t38, :t39, :t40, :t41, :t42, :t43, :t44, :t45, :t46, :t47, :t48, :t49, :t50, :t51, :t52, :t53, :t54, :t55, :t56, :t57, :t58, :t59, :t60, :t61, :t62, :t63, :t64, :t65, :t66, :t67, :t68, :t69, :t70, :t71, :t72, :t73, :t74, :t75, :t76, :t77, :t78, :t79, :t80, :t81, :t82, :t83, :t84, :t85, :t86, :t87, :t88, :t89, :t90, :t91, :t92, :t93, :t94, :t95, :t96, :t97, :t98, :t99)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kine_helper.rb
module KineHelper
end

app/views/kine/disable.index.json.erb
<%= @kineHash.map{|cow| cow.map{|e| "#{e[0].to_s} : #{e[1]}"}} %>

app/views/kine/edit.html.erb
<h1>Editing cow</h1>

<%= render 'form' %>

<%= link_to 'Show', @cow %> |
<%= link_to 'Back', kine_path %>

app/views/kine/index.html.erb
<h1>Listing kine</h1>

<%= form_tag kine_path, :method => 'get' do %>
  <p>
    name: <%= text_field_tag :search, params[:search] %>
    owner: <%= text_field_tag :search_owner, params[:search_owner] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ear</th>
      <th>Birth</th>
      <th>Owner</th>
      <th>T01</th>
      <th>T02</th>
      <th>T03</th>
      <th>T04</th>
      <th>T05</th>
      <th>T06</th>
      <th>T07</th>
      <th>T08</th>
      <th>T09</th>
      <th>T10</th>
      <th>T11</th>
      <th>T12</th>
      <th>T13</th>
      <th>T14</th>
      <th>T15</th>
      <th>T16</th>
      <th>T17</th>
      <th>T18</th>
      <th>T19</th>
      <th>T20</th>
      <th>T21</th>
      <th>T22</th>
      <th>T23</th>
      <th>T24</th>
      <th>T25</th>
      <th>T26</th>
      <th>T27</th>
      <th>T28</th>
      <th>T29</th>
      <th>T30</th>
      <th>T31</th>
      <th>T32</th>
      <th>T33</th>
      <th>T34</th>
      <th>T35</th>
      <th>T36</th>
      <th>T37</th>
      <th>T38</th>
      <th>T39</th>
      <th>T40</th>
      <th>T41</th>
      <th>T42</th>
      <th>T43</th>
      <th>T44</th>
      <th>T45</th>
      <th>T46</th>
      <th>T47</th>
      <th>T48</th>
      <th>T49</th>
      <th>T50</th>
      <th>T51</th>
      <th>T52</th>
      <th>T53</th>
      <th>T54</th>
      <th>T55</th>
      <th>T56</th>
      <th>T57</th>
      <th>T58</th>
      <th>T59</th>
      <th>T60</th>
      <th>T61</th>
      <th>T62</th>
      <th>T63</th>
      <th>T64</th>
      <th>T65</th>
      <th>T66</th>
      <th>T67</th>
      <th>T68</th>
      <th>T69</th>
      <th>T70</th>
      <th>T71</th>
      <th>T72</th>
      <th>T73</th>
      <th>T74</th>
      <th>T75</th>
      <th>T76</th>
      <th>T77</th>
      <th>T78</th>
      <th>T79</th>
      <th>T80</th>
      <th>T81</th>
      <th>T82</th>
      <th>T83</th>
      <th>T84</th>
      <th>T85</th>
      <th>T86</th>
      <th>T87</th>
      <th>T88</th>
      <th>T89</th>
      <th>T90</th>
      <th>T91</th>
      <th>T92</th>
      <th>T93</th>
      <th>T94</th>
      <th>T95</th>
      <th>T96</th>
      <th>T97</th>
      <th>T98</th>
      <th>T99</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @kine.each do |cow| %>
      <tr>
        <td><%= cow.name %></td>
        <td><%= cow.ear %></td>
        <td><%= cow.birth %></td>
        <td><%= cow.owner_id %></td>
        <td><%= cow.t01 %></td>
        <td><%= cow.t02 %></td>
        <td><%= cow.t03 %></td>
        <td><%= cow.t04 %></td>
        <td><%= cow.t05 %></td>
        <td><%= cow.t06 %></td>
        <td><%= cow.t07 %></td>
        <td><%= cow.t08 %></td>
        <td><%= cow.t09 %></td>
        <td><%= cow.t10 %></td>
        <td><%= cow.t11 %></td>
        <td><%= cow.t12 %></td>
        <td><%= cow.t13 %></td>
        <td><%= cow.t14 %></td>
        <td><%= cow.t15 %></td>
        <td><%= cow.t16 %></td>
        <td><%= cow.t17 %></td>
        <td><%= cow.t18 %></td>
        <td><%= cow.t19 %></td>
        <td><%= cow.t20 %></td>
        <td><%= cow.t21 %></td>
        <td><%= cow.t22 %></td>
        <td><%= cow.t23 %></td>
        <td><%= cow.t24 %></td>
        <td><%= cow.t25 %></td>
        <td><%= cow.t26 %></td>
        <td><%= cow.t27 %></td>
        <td><%= cow.t28 %></td>
        <td><%= cow.t29 %></td>
        <td><%= cow.t30 %></td>
        <td><%= cow.t31 %></td>
        <td><%= cow.t32 %></td>
        <td><%= cow.t33 %></td>
        <td><%= cow.t34 %></td>
        <td><%= cow.t35 %></td>
        <td><%= cow.t36 %></td>
        <td><%= cow.t37 %></td>
        <td><%= cow.t38 %></td>
        <td><%= cow.t39 %></td>
        <td><%= cow.t40 %></td>
        <td><%= cow.t41 %></td>
        <td><%= cow.t42 %></td>
        <td><%= cow.t43 %></td>
        <td><%= cow.t44 %></td>
        <td><%= cow.t45 %></td>
        <td><%= cow.t46 %></td>
        <td><%= cow.t47 %></td>
        <td><%= cow.t48 %></td>
        <td><%= cow.t49 %></td>
        <td><%= cow.t50 %></td>
        <td><%= cow.t51 %></td>
        <td><%= cow.t52 %></td>
        <td><%= cow.t53 %></td>
        <td><%= cow.t54 %></td>
        <td><%= cow.t55 %></td>
        <td><%= cow.t56 %></td>
        <td><%= cow.t57 %></td>
        <td><%= cow.t58 %></td>
        <td><%= cow.t59 %></td>
        <td><%= cow.t60 %></td>
        <td><%= cow.t61 %></td>
        <td><%= cow.t62 %></td>
        <td><%= cow.t63 %></td>
        <td><%= cow.t64 %></td>
        <td><%= cow.t65 %></td>
        <td><%= cow.t66 %></td>
        <td><%= cow.t67 %></td>
        <td><%= cow.t68 %></td>
        <td><%= cow.t69 %></td>
        <td><%= cow.t70 %></td>
        <td><%= cow.t71 %></td>
        <td><%= cow.t72 %></td>
        <td><%= cow.t73 %></td>
        <td><%= cow.t74 %></td>
        <td><%= cow.t75 %></td>
        <td><%= cow.t76 %></td>
        <td><%= cow.t77 %></td>
        <td><%= cow.t78 %></td>
        <td><%= cow.t79 %></td>
        <td><%= cow.t80 %></td>
        <td><%= cow.t81 %></td>
        <td><%= cow.t82 %></td>
        <td><%= cow.t83 %></td>
        <td><%= cow.t84 %></td>
        <td><%= cow.t85 %></td>
        <td><%= cow.t86 %></td>
        <td><%= cow.t87 %></td>
        <td><%= cow.t88 %></td>
        <td><%= cow.t89 %></td>
        <td><%= cow.t90 %></td>
        <td><%= cow.t91 %></td>
        <td><%= cow.t92 %></td>
        <td><%= cow.t93 %></td>
        <td><%= cow.t94 %></td>
        <td><%= cow.t95 %></td>
        <td><%= cow.t96 %></td>
        <td><%= cow.t97 %></td>
        <td><%= cow.t98 %></td>
        <td><%= cow.t99 %></td>
        <td><%= link_to 'Show', cow %></td>
        <td><%= link_to 'Edit', edit_cow_path(cow) %></td>
        <td><%= link_to 'Destroy', cow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cow', new_cow_path %>

app/views/kine/new.html.erb
<h1>New cow</h1>

<%= render 'form' %>

<%= link_to 'Back', kine_path %>

app/views/kine/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cow.name %>
</p>

<p>
  <strong>Ear:</strong>
  <%= @cow.ear %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @cow.birth %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @cow.owner_id %>
</p>

<p>
  <strong>T01:</strong>
  <%= @cow.t01 %>
</p>

<p>
  <strong>T02:</strong>
  <%= @cow.t02 %>
</p>

<p>
  <strong>T03:</strong>
  <%= @cow.t03 %>
</p>

<p>
  <strong>T04:</strong>
  <%= @cow.t04 %>
</p>

<p>
  <strong>T05:</strong>
  <%= @cow.t05 %>
</p>

<p>
  <strong>T06:</strong>
  <%= @cow.t06 %>
</p>

<p>
  <strong>T07:</strong>
  <%= @cow.t07 %>
</p>

<p>
  <strong>T08:</strong>
  <%= @cow.t08 %>
</p>

<p>
  <strong>T09:</strong>
  <%= @cow.t09 %>
</p>

<p>
  <strong>T10:</strong>
  <%= @cow.t10 %>
</p>

<p>
  <strong>T11:</strong>
  <%= @cow.t11 %>
</p>

<p>
  <strong>T12:</strong>
  <%= @cow.t12 %>
</p>

<p>
  <strong>T13:</strong>
  <%= @cow.t13 %>
</p>

<p>
  <strong>T14:</strong>
  <%= @cow.t14 %>
</p>

<p>
  <strong>T15:</strong>
  <%= @cow.t15 %>
</p>

<p>
  <strong>T16:</strong>
  <%= @cow.t16 %>
</p>

<p>
  <strong>T17:</strong>
  <%= @cow.t17 %>
</p>

<p>
  <strong>T18:</strong>
  <%= @cow.t18 %>
</p>

<p>
  <strong>T19:</strong>
  <%= @cow.t19 %>
</p>

<p>
  <strong>T20:</strong>
  <%= @cow.t20 %>
</p>

<p>
  <strong>T21:</strong>
  <%= @cow.t21 %>
</p>

<p>
  <strong>T22:</strong>
  <%= @cow.t22 %>
</p>

<p>
  <strong>T23:</strong>
  <%= @cow.t23 %>
</p>

<p>
  <strong>T24:</strong>
  <%= @cow.t24 %>
</p>

<p>
  <strong>T25:</strong>
  <%= @cow.t25 %>
</p>

<p>
  <strong>T26:</strong>
  <%= @cow.t26 %>
</p>

<p>
  <strong>T27:</strong>
  <%= @cow.t27 %>
</p>

<p>
  <strong>T28:</strong>
  <%= @cow.t28 %>
</p>

<p>
  <strong>T29:</strong>
  <%= @cow.t29 %>
</p>

<p>
  <strong>T30:</strong>
  <%= @cow.t30 %>
</p>

<p>
  <strong>T31:</strong>
  <%= @cow.t31 %>
</p>

<p>
  <strong>T32:</strong>
  <%= @cow.t32 %>
</p>

<p>
  <strong>T33:</strong>
  <%= @cow.t33 %>
</p>

<p>
  <strong>T34:</strong>
  <%= @cow.t34 %>
</p>

<p>
  <strong>T35:</strong>
  <%= @cow.t35 %>
</p>

<p>
  <strong>T36:</strong>
  <%= @cow.t36 %>
</p>

<p>
  <strong>T37:</strong>
  <%= @cow.t37 %>
</p>

<p>
  <strong>T38:</strong>
  <%= @cow.t38 %>
</p>

<p>
  <strong>T39:</strong>
  <%= @cow.t39 %>
</p>

<p>
  <strong>T40:</strong>
  <%= @cow.t40 %>
</p>

<p>
  <strong>T41:</strong>
  <%= @cow.t41 %>
</p>

<p>
  <strong>T42:</strong>
  <%= @cow.t42 %>
</p>

<p>
  <strong>T43:</strong>
  <%= @cow.t43 %>
</p>

<p>
  <strong>T44:</strong>
  <%= @cow.t44 %>
</p>

<p>
  <strong>T45:</strong>
  <%= @cow.t45 %>
</p>

<p>
  <strong>T46:</strong>
  <%= @cow.t46 %>
</p>

<p>
  <strong>T47:</strong>
  <%= @cow.t47 %>
</p>

<p>
  <strong>T48:</strong>
  <%= @cow.t48 %>
</p>

<p>
  <strong>T49:</strong>
  <%= @cow.t49 %>
</p>

<p>
  <strong>T50:</strong>
  <%= @cow.t50 %>
</p>

<p>
  <strong>T51:</strong>
  <%= @cow.t51 %>
</p>

<p>
  <strong>T52:</strong>
  <%= @cow.t52 %>
</p>

<p>
  <strong>T53:</strong>
  <%= @cow.t53 %>
</p>

<p>
  <strong>T54:</strong>
  <%= @cow.t54 %>
</p>

<p>
  <strong>T55:</strong>
  <%= @cow.t55 %>
</p>

<p>
  <strong>T56:</strong>
  <%= @cow.t56 %>
</p>

<p>
  <strong>T57:</strong>
  <%= @cow.t57 %>
</p>

<p>
  <strong>T58:</strong>
  <%= @cow.t58 %>
</p>

<p>
  <strong>T59:</strong>
  <%= @cow.t59 %>
</p>

<p>
  <strong>T60:</strong>
  <%= @cow.t60 %>
</p>

<p>
  <strong>T61:</strong>
  <%= @cow.t61 %>
</p>

<p>
  <strong>T62:</strong>
  <%= @cow.t62 %>
</p>

<p>
  <strong>T63:</strong>
  <%= @cow.t63 %>
</p>

<p>
  <strong>T64:</strong>
  <%= @cow.t64 %>
</p>

<p>
  <strong>T65:</strong>
  <%= @cow.t65 %>
</p>

<p>
  <strong>T66:</strong>
  <%= @cow.t66 %>
</p>

<p>
  <strong>T67:</strong>
  <%= @cow.t67 %>
</p>

<p>
  <strong>T68:</strong>
  <%= @cow.t68 %>
</p>

<p>
  <strong>T69:</strong>
  <%= @cow.t69 %>
</p>

<p>
  <strong>T70:</strong>
  <%= @cow.t70 %>
</p>

<p>
  <strong>T71:</strong>
  <%= @cow.t71 %>
</p>

<p>
  <strong>T72:</strong>
  <%= @cow.t72 %>
</p>

<p>
  <strong>T73:</strong>
  <%= @cow.t73 %>
</p>

<p>
  <strong>T74:</strong>
  <%= @cow.t74 %>
</p>

<p>
  <strong>T75:</strong>
  <%= @cow.t75 %>
</p>

<p>
  <strong>T76:</strong>
  <%= @cow.t76 %>
</p>

<p>
  <strong>T77:</strong>
  <%= @cow.t77 %>
</p>

<p>
  <strong>T78:</strong>
  <%= @cow.t78 %>
</p>

<p>
  <strong>T79:</strong>
  <%= @cow.t79 %>
</p>

<p>
  <strong>T80:</strong>
  <%= @cow.t80 %>
</p>

<p>
  <strong>T81:</strong>
  <%= @cow.t81 %>
</p>

<p>
  <strong>T82:</strong>
  <%= @cow.t82 %>
</p>

<p>
  <strong>T83:</strong>
  <%= @cow.t83 %>
</p>

<p>
  <strong>T84:</strong>
  <%= @cow.t84 %>
</p>

<p>
  <strong>T85:</strong>
  <%= @cow.t85 %>
</p>

<p>
  <strong>T86:</strong>
  <%= @cow.t86 %>
</p>

<p>
  <strong>T87:</strong>
  <%= @cow.t87 %>
</p>

<p>
  <strong>T88:</strong>
  <%= @cow.t88 %>
</p>

<p>
  <strong>T89:</strong>
  <%= @cow.t89 %>
</p>

<p>
  <strong>T90:</strong>
  <%= @cow.t90 %>
</p>

<p>
  <strong>T91:</strong>
  <%= @cow.t91 %>
</p>

<p>
  <strong>T92:</strong>
  <%= @cow.t92 %>
</p>

<p>
  <strong>T93:</strong>
  <%= @cow.t93 %>
</p>

<p>
  <strong>T94:</strong>
  <%= @cow.t94 %>
</p>

<p>
  <strong>T95:</strong>
  <%= @cow.t95 %>
</p>

<p>
  <strong>T96:</strong>
  <%= @cow.t96 %>
</p>

<p>
  <strong>T97:</strong>
  <%= @cow.t97 %>
</p>

<p>
  <strong>T98:</strong>
  <%= @cow.t98 %>
</p>

<p>
  <strong>T99:</strong>
  <%= @cow.t99 %>
</p>

<%= link_to 'Edit', edit_cow_path(@cow) %> |
<%= link_to 'Back', kine_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LargeDb2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>